// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_5f717cd185967492, []int{0}
}
func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (dst *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(dst, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SessionGrant struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionGrant) Reset()         { *m = SessionGrant{} }
func (m *SessionGrant) String() string { return proto.CompactTextString(m) }
func (*SessionGrant) ProtoMessage()    {}
func (*SessionGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_5f717cd185967492, []int{1}
}
func (m *SessionGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionGrant.Unmarshal(m, b)
}
func (m *SessionGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionGrant.Marshal(b, m, deterministic)
}
func (dst *SessionGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionGrant.Merge(dst, src)
}
func (m *SessionGrant) XXX_Size() int {
	return xxx_messageInfo_SessionGrant.Size(m)
}
func (m *SessionGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionGrant.DiscardUnknown(m)
}

var xxx_messageInfo_SessionGrant proto.InternalMessageInfo

func (m *SessionGrant) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SessionGrant) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*SessionRequest)(nil), "gameproto.v1.SessionRequest")
	proto.RegisterType((*SessionGrant)(nil), "gameproto.v1.SessionGrant")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionClient interface {
	NewSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionGrant, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) NewSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionGrant, error) {
	out := new(SessionGrant)
	err := c.cc.Invoke(ctx, "/gameproto.v1.Session/NewSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServer is the server API for Session service.
type SessionServer interface {
	NewSession(context.Context, *SessionRequest) (*SessionGrant, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gameproto.v1.Session/NewSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).NewSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gameproto.v1.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSession",
			Handler:    _Session_NewSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_5f717cd185967492) }

var fileDescriptor_game_5f717cd185967492 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xb1, 0xc1, 0x4c, 0xbd, 0x32, 0x43, 0x25,
	0x0f, 0x2e, 0xbe, 0xe0, 0xd4, 0xe2, 0xe2, 0xcc, 0xfc, 0xbc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22,
	0xc1, 0x04, 0x91, 0x83, 0xf1, 0x95, 0xac, 0xb8, 0x78, 0xa0, 0x26, 0xb9, 0x17, 0x25, 0xe6, 0x95,
	0x08, 0x09, 0x71, 0xb1, 0x94, 0x96, 0x66, 0xa6, 0x40, 0xcd, 0x00, 0xb3, 0x85, 0xc4, 0xb8, 0xd8,
	0x8a, 0x52, 0x13, 0x8b, 0xf3, 0xf3, 0xa0, 0xba, 0xa1, 0x3c, 0xa3, 0x40, 0x2e, 0x76, 0xa8, 0x5e,
	0x21, 0x37, 0x2e, 0x2e, 0xbf, 0xd4, 0x72, 0x18, 0x4f, 0x46, 0x0f, 0xd9, 0xb5, 0x7a, 0xa8, 0x4e,
	0x95, 0x92, 0xc2, 0x2a, 0x0b, 0xb6, 0xde, 0x89, 0x3d, 0x8a, 0x15, 0x2c, 0x91, 0xc4, 0x06, 0xa6,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0x73, 0x3e, 0xca, 0x04, 0x01, 0x00, 0x00,
}
